export const dialogues = [
    { speaker: "", text: "On the way to school..." },
    { speaker: "NAGISA", text: "Anpan" },
    { speaker: "TOMOYA", text: "That sounded serious." },
    { speaker: "NAGISA", text: "Good morning, Okazaki-san." },
    { speaker: "TOMOYA", text: "Morning. Are you declaring war on breakfast?" },
    { speaker: "NAGISA", text: "No. I was trying to give myself courage." },
    { speaker: "TOMOYA", text: "Using bread." },
    { speaker: "NAGISA", text: "Bread is dependable." },
    { speaker: "", text: "As they climb the hill together, something inside Nagisa's school bag knocks softly against the clasp with every step." },
    { speaker: "TOMOYA", text: "You’ve got a contraband in there?" },
    { speaker: "NAGISA", text: "I don’t think it counts as contraband." },
    { speaker: "TOMOYA", text: "That’s exactly what someone carrying contraband would say." },
    { speaker: "", text: "Nagisa opens the bag just enough to show him an old brass key tied to a cracked wooden tag: CLUB — STORAGE." },
    { speaker: "NAGISA", text: "Koumura-sensei lent it to me yesterday. He said the old clubroom has to be inventoried before we can ask to use anything." },
    { speaker: "TOMOYA", text: "And by ‘we,’ he meant you." },
    { speaker: "NAGISA", text: "He may have meant me." },
    { speaker: "TOMOYA", text: "A tragic misunderstanding." },
    { speaker: "NAGISA", text: "I thought I would do it after class. If I know what is there, perhaps I can plan something small for recruitment." },
    { speaker: "NAGISA", text: "If you are not busy—" },
    { speaker: "TOMOYA", text: "I’m extremely busy." },
    { speaker: "TOMOYA", text: "I have to avoid class, annoy Sunohara, stare out a window, and preserve my reputation. It’s a packed schedule you know." },
    { speaker: "NAGISA", text: "Would the preservation of your reputation allow thirty minutes for the drama club?" },
    { speaker: "TOMOYA", text: "Twenty." },
    { speaker: "NAGISA", text: "Twenty-five?" },
    { speaker: "TOMOYA", text: "You bargain like a shopkeeper." },
    { speaker: "NAGISA", text: "My family owns a bakery." },
    { speaker: "TOMOYA", text: "Fine. Thirty." },
    { speaker: "NAGISA", text: "Then I will bring you one of today's breads as thanks." },
    { speaker: "TOMOYA", text: "A normal one?" },
    { speaker: "NAGISA", text: "A normal one." },
    { speaker: "NAGISA", text: "Thank you very much." },
