export const dialogues = [
    { speaker: "", text: "On the way to school..." },
    { speaker: "NAGISA", text: "Anpan." },
    { speaker: "TOMOYA", text: "That sounded serious." },
    { speaker: "NAGISA", text: "Good morning, Okazaki-san." },
    { speaker: "TOMOYA", text: "Morning. Are you declaring war on breakfast?" },
    { speaker: "NAGISA", text: "No. I was trying to give myself courage." },
    { speaker: "TOMOYA", text: "Using bread." },
    { speaker: "NAGISA", text: "Bread is dependable." },
    { speaker: "", text: "As they climb the hill together, something inside Nagisa's school bag knocks softly against the clasp with every step." },
    { speaker: "TOMOYA", text: "You’ve got contraband in there." },
    { speaker: "NAGISA", text: "I don’t think it counts as contraband." },
    { speaker: "TOMOYA", text: "That’s exactly what someone carrying contraband would say." },
    { speaker: "", text: "Nagisa opens the bag just enough to show him an old brass key tied to a cracked wooden tag: CLUB — STORAGE." },
    { speaker: "NAGISA", text: "Koumura-sensei lent it to me yesterday. He said the old clubroom has to be inventoried before we can ask to use anything." },
    { speaker: "TOMOYA", text: "And by ‘we,’ he meant you." },
    { speaker: "NAGISA", text: "He may have meant me." },
    { speaker: "TOMOYA", text: "A tragic misunderstanding." },
    { speaker: "NAGISA", text: "I thought I would do it after class. If I know what is there, perhaps I can plan something small for recruitment." },
    { speaker: "NAGISA", text: "If you are not busy—" },
    { speaker: "TOMOYA", text: "I’m extremely busy." },
    { speaker: "TOMOYA", text: "I have to avoid class, annoy Sunohara, stare out a window, and preserve my reputation. It’s a packed schedule." },
    { speaker: "NAGISA", text: "Would the preservation of your reputation allow thirty minutes for the drama club?" },
    { speaker: "TOMOYA", text: "Twenty." },
    { speaker: "NAGISA", text: "Twenty-five?" },
    { speaker: "TOMOYA", text: "You bargain like a shopkeeper." },
    { speaker: "NAGISA", text: "My family owns a bakery." },
    { speaker: "TOMOYA", text: "Fine. Thirty." },
    { speaker: "NAGISA", text: "Then I will bring you one of today's breads as thanks." },
    { speaker: "TOMOYA", text: "A normal one?" },
    { speaker: "NAGISA", text: "A normal one." },
    { speaker: "NAGISA", text: "Thank you very much." },
    { speaker: "NAGISA", text: "Okazaki-san." },
    { speaker: "TOMOYA", text: "What?" },
    { speaker: "NAGISA", text: "Your reputation is already very strong. I don’t think thirty minutes will damage it." },
    { speaker: "", text: "A little later, in class..." },
    { speaker: "RYOU", text: "Furukawa-san asked me to remind you about the clubroom after class." },
    { speaker: "TOMOYA", text: "She thinks I’ll try to escape?" },
    { speaker: "RYOU", text: "She said you might forget." },
    { speaker: "TOMOYA", text: "That’s a much nicer way of saying it." },
    { speaker: "KYOU", text: "Stop making that face at Ryou." },
    { speaker: "TOMOYA", text: "What face?" },
    { speaker: "KYOU", text: "The one that says you’re about to waste everyone’s time." },
    { speaker: "TOMOYA", text: "That’s just my face." },
    { speaker: "KYOU", text: "Unfortunate." },
    { speaker: "SUNOHARA", text: "What are you talking about?" },
    { speaker: "TOMOYA", text: "Furukawa recruited me to clean the old clubroom." },
    { speaker: "SUNOHARA", text: "Sounds awful. Good luck with that." },
    { speaker: "TOMOYA", text: "You’re coming too." },
    { speaker: "SUNOHARA", text: "Why me?" },
    { speaker: "TOMOYA", text: "You look qualified." },
    { speaker: "", text: "At lunch, Nagisa brings Tomoya the bread she promised." },
    { speaker: "NAGISA", text: "As promised." },
    { speaker: "TOMOYA", text: "What’s in it?" },
    { speaker: "NAGISA", text: "Sweet bean paste." },
    { speaker: "TOMOYA", text: "Only sweet bean paste?" },
    { speaker: "NAGISA", text: "Yes." },
    { speaker: "TOMOYA", text: "No kelp? No pickled radish? No philosophical concept your mother decided to bake at four in the morning?" },
    { speaker: "NAGISA", text: "Mother’s breads are made with a great deal of thought." },
    { speaker: "TOMOYA", text: "That wasn’t a no." },
    { speaker: "NAGISA", text: "It is for you." },
    { speaker: "TOMOYA", text: "Payment before the work is finished encourages corruption." },
    { speaker: "NAGISA", text: "Then I will help prevent corruption." },
    { speaker: "", text: "Nagisa opens a cloth bundle containing a notebook, two masks, work gloves, and three neatly folded cleaning cloths." },
    { speaker: "TOMOYA", text: "You came prepared for an archaeological expedition." },
    { speaker: "NAGISA", text: "Old clubs leave many things behind." },
    { speaker: "", text: "Her inventory page has columns for item, condition, and possible use." },
    { speaker: "TOMOYA", text: "Possible use?" },
    { speaker: "NAGISA", text: "If we find anything helpful, I would like to use it for a short recruitment performance." },
    { speaker: "TOMOYA", text: "You’re going to perform before the club exists?" },
    { speaker: "NAGISA", text: "If we wait for members before showing them what the club can do, no one may join." },
    { speaker: "TOMOYA", text: "How short is short?" },
    { speaker: "NAGISA", text: "One minute." },
    { speaker: "TOMOYA", text: "That’s not a play. That’s an apology." },
    { speaker: "NAGISA", text: "It can still have a beginning, a middle, and an end." },
    { speaker: "TOMOYA", text: "Beginning: the drama club needs members. Middle: nobody joins. End: the club is dissolved again." },
    { speaker: "TOMOYA", text: "Or a mysterious delinquent saves it at the last second." },
    { speaker: "NAGISA", text: "Would he?" },
    { speaker: "TOMOYA", text: "No. He has a reputation to preserve." },
    { speaker: "NAGISA", text: "Then perhaps someone will persuade him." },
    { speaker: "NAGISA", text: "The old room is in the west wing. I will meet you outside your classroom." },
    { speaker: "TOMOYA", text: "Forty minutes." },
    { speaker: "NAGISA", text: "Forty-five." },
    { speaker: "TOMOYA", text: "You’re getting worse." },
    { speaker: "NAGISA", text: "Thank you." },
    { speaker: "", text: "After class, Nagisa unlocks the old clubroom with Koumura-sensei's key, but the door opens only three centimeters." },
    { speaker: "NAGISA", text: "It will not open any farther." },
    { speaker: "TOMOYA", text: "Something’s blocking it." },
    { speaker: "NAGISA", text: "Can we move it?" },
    { speaker: "TOMOYA", text: "Probably." },
    { speaker: "NAGISA", text: "How?" },
    { speaker: "", text: "Sunohara, whom Tomoya volunteered for the job in class, tries to slip away." },
    { speaker: "TOMOYA", text: "We use a tool." },
    { speaker: "SUNOHARA", text: "Don’t look at me like that." },
    { speaker: "SUNOHARA", text: "If I die, tell everyone I was rescuing a puppy." },
    { speaker: "TOMOYA", text: "We’ll tell them you were defeated by a door." },
    { speaker: "SUNOHARA", text: "That’s exactly why I asked you not to handle it." },
    { speaker: "", text: "Sunohara squeezes through the gap and pushes the fallen backdrop aside." },
    { speaker: "SUNOHARA", text: "Behold. The king has returned." },
    { speaker: "", text: "Nagisa claps once before she can stop herself." },
    { speaker: "SUNOHARA", text: "At least Furukawa understands stage presence." },
    { speaker: "NAGISA", text: "We should begin with the cabinets." },
    { speaker: "TOMOYA", text: "Sunohara, you heard the president." },
    { speaker: "SUNOHARA", text: "She’s not president yet." },
    { speaker: "TOMOYA", text: "Disrespecting the crown’s natural enemy is treason." },
    { speaker: "", text: "Among the stage props, they find a folding cardboard house with a blue door, two windows, and six smiling round faces along its roof." },
    { speaker: "NAGISA", text: "They look like a family." },
    { speaker: "TOMOYA", text: "They look like dumplings that took out a mortgage." },
    { speaker: "NAGISA", text: "That can also be a family." },
    { speaker: "TOMOYA", text: "You’ve already decided, haven’t you?" },
    { speaker: "NAGISA", text: "It could be the set for the recruitment performance." },
    { speaker: "TOMOYA", text: "The one-minute apology." },
    { speaker: "NAGISA", text: "It may be ninety seconds now." },
    { speaker: "SUNOHARA", text: "With an actor of my caliber, you’ll need at least ten minutes." },
    { speaker: "", text: "A loose cardboard window drops onto Sunohara's head." },
    { speaker: "TOMOYA", text: "The house has rejected your audition." },
    { speaker: "", text: "When they carry the prop outside, it starts raining." },
    { speaker: "SUNOHARA", text: "We can leave it here." },
    { speaker: "NAGISA", text: "The hallway ceiling leaks near the old room. Koumura-sensei said everything valuable should be moved somewhere dry." },
    { speaker: "TOMOYA", text: "This is valuable?" },
    { speaker: "NAGISA", text: "It might be." },
    { speaker: "NAGISA", text: "He said I may keep any useful props at home until we have a dry clubroom." },
    { speaker: "SUNOHARA", text: "I have urgent dormitory business." },
    { speaker: "TOMOYA", text: "Name one piece of business." },
    { speaker: "SUNOHARA", text: "Maintaining morale." },
    { speaker: "TOMOYA", text: "Whose?" },
    { speaker: "SUNOHARA", text: "Mine." },
    { speaker: "", text: "At the entrance, Kyou and Ryou stop to help cover the prop." },
    { speaker: "KYOU", text: "Why are you carrying a house?" },
    { speaker: "TOMOYA", text: "Rent is cheaper outside the school district." },
    { speaker: "KYOU", text: "I asked Furukawa." },
    { speaker: "", text: "Nagisa explains the leaking clubroom and her plan to keep the prop dry at home." },
    { speaker: "KYOU", text: "The plastic sheet from the gym storage." },
    { speaker: "RYOU", text: "I’ll get it." },
    { speaker: "KYOU", text: "No, stay here. I’m faster." },
    { speaker: "KYOU", text: "Hold this." },
    { speaker: "SUNOHARA", text: "She gave me her umbrella." },
    { speaker: "TOMOYA", text: "Try not to build a future around it." },
    { speaker: "", text: "Kyou returns with a plastic sheet and tape. They wrap the cardboard prop, and she takes her umbrella back from Sunohara." },
    { speaker: "RYOU", text: "Will you be all right carrying it?" },
    { speaker: "NAGISA", text: "Yes. My home is not far." },
    { speaker: "KYOU", text: "Make Sunohara carry the heavy end." },
    { speaker: "SUNOHARA", text: "I have a delicate spine." },
    { speaker: "KYOU", text: "Then it won’t be missed." },
    { speaker: "", text: "Sunohara helps as far as the school gate, then runs toward the dormitory with his school bag held over his head." },
    { speaker: "NAGISA", text: "Do you think he really has an appointment?" },
    { speaker: "TOMOYA", text: "Yes. Misae-san probably scheduled his execution weeks ago." },
    { speaker: "NAGISA", text: "We can manage." },
    { speaker: "TOMOYA", text: "That sentence has caused most disasters in history." },
    { speaker: "TOMOYA", text: "This isn’t working." },
    { speaker: "NAGISA", text: "We are sharing fairly." },
    { speaker: "TOMOYA", text: "We’re failing fairly." },
    { speaker: "NAGISA", text: "That is still fair." },
    { speaker: "", text: "An old woman watching from beneath a shop awning calls, ‘Moving day?’" },
    { speaker: "TOMOYA", text: "We found a place near the station." },
    { speaker: "", text: "A gust tears the blue cardboard door loose and sends it skating across the wet street." },
    { speaker: "NAGISA", text: "The door!" },
    { speaker: "TOMOYA", text: "The house is getting ideas." },
    { speaker: "", text: "They leave the house beneath an awning and chase the door. Tomoya reaches it first and plants one shoe on its corner before it can escape through a railing." },
    { speaker: "NAGISA", text: "You caught it." },
    { speaker: "TOMOYA", text: "That’s what delinquents do. We stand on doors." },
    { speaker: "NAGISA", text: "It is damaged." },
    { speaker: "TOMOYA", text: "Not much." },
    { speaker: "NAGISA", text: "I should have taped it more carefully." },
    { speaker: "TOMOYA", text: "Then it would have flown farther with the extra weight." },
    { speaker: "NAGISA", text: "That is not how weight works." },
    { speaker: "TOMOYA", text: "You’re becoming difficult to deceive." },
    { speaker: "NAGISA", text: "I’m sorry." },
    { speaker: "TOMOYA", text: "For what?" },
    { speaker: "NAGISA", text: "Your uniform is wet. The inventory took more than forty-five minutes. Sunohara-san had to help. Ryou-san and Kyou-san had to help. And now the prop is damaged." },
    { speaker: "TOMOYA", text: "You forgot the part where the town thinks we’re newlyweds who made a terrible housing decision." },
    { speaker: "", text: "Nagisa goes very still, and Tomoya abruptly finds the rain fascinating." },
    { speaker: "TOMOYA", text: "That was a joke." },
    { speaker: "NAGISA", text: "Yes." },
    { speaker: "TOMOYA", text: "A bad one." },
    { speaker: "NAGISA", text: "I understood it." },
    { speaker: "TOMOYA", text: "That makes one of us." },
    { speaker: "NAGISA", text: "I do not think the house is terrible." },
    { speaker: "TOMOYA", text: "The door just tried to leave." },
    { speaker: "NAGISA", text: "Perhaps it wanted to see the town." },
    { speaker: "TOMOYA", text: "You’re defending it?" },
    { speaker: "NAGISA", text: "It has been shut in a room for a long time." },
    { speaker: "", text: "A little boy passing by points at the round faces and calls them dango." },
    { speaker: "NAGISA", text: "He thinks they are dango." },
    { speaker: "TOMOYA", text: "He’s young. He still has time to learn." },
    { speaker: "NAGISA", text: "They could be a big dango family." },
    { speaker: "TOMOYA", text: "Living in a house without a door." },
    { speaker: "NAGISA", text: "We will repair it." },
    { speaker: "NAGISA", text: "The performance can be about a house waiting for its family to return." },
    { speaker: "TOMOYA", text: "That’s depressing for a recruitment event." },
    { speaker: "NAGISA", text: "They return at the end." },
    { speaker: "TOMOYA", text: "Spoilers." },
    { speaker: "NAGISA", text: "The house believes they will come back, even when it is alone." },
    { speaker: "NAGISA", text: "Someone only needs to keep one light on." },
    { speaker: "TOMOYA", text: "Ninety seconds won’t be enough." },
    { speaker: "TOMOYA", text: "Make it two minutes." },
    { speaker: "NAGISA", text: "Two minutes." },
    { speaker: "", text: "They finally make it to Furukawa Bread." },
    { speaker: "SANAE", text: "Welcome home, Nagisa. And welcome, Okazaki-san. Oh—have you brought a wall?" },
    { speaker: "TOMOYA", text: "Most customers start with bread. We wanted to make an impression." },
    { speaker: "AKIO", text: "Boy." },
    { speaker: "TOMOYA", text: "Old man." },
    { speaker: "AKIO", text: "Explain why my daughter has returned in the rain with a strange man and half a house." },
    { speaker: "TOMOYA", text: "The other half won custody." },
    { speaker: "AKIO", text: "So this is how you planned to do it. You couldn’t afford a proper place, so you brought the front of one and hoped we wouldn’t notice." },
    { speaker: "NAGISA", text: "Papa, it is a stage prop." },
    { speaker: "AKIO", text: "A stage prop?" },
    { speaker: "NAGISA", text: "For the drama club." },
    { speaker: "AKIO", text: "Weak foundation. Poor weatherproofing. Door missing. Location excellent." },
    { speaker: "TOMOYA", text: "It attempted to relocate." },
    { speaker: "SANAE", text: "Then we should welcome it back." },
    { speaker: "", text: "A little later, Sunohara arrives dripping wet. He claims his ‘official dormitory business’ ended early and that helping carry the prop earned him dinner, then reaches for one of Sanae's purple breads." },
    { speaker: "SUNOHARA", text: "What?" },
    { speaker: "TOMOYA", text: "Think about everything you still want to accomplish." },
    { speaker: "SANAE", text: "Is my bread preventing your dreams?" },
    { speaker: "SANAE", text: "I knew it was too ambitious!" },
    { speaker: "", text: "Sanae runs from the bakery in tears. Akio drops his screwdriver and races after her." },
    { speaker: "AKIO", text: "Sanae! I love ambition!" },
    { speaker: "SUNOHARA", text: "Does this happen every day?" },
    { speaker: "NAGISA", text: "Not every day." },
    { speaker: "NAGISA", text: "Some days Mother is more confident." },
    { speaker: "TOMOYA", text: "Those are the dangerous days." },
    { speaker: "", text: "While they repair the prop, Nagisa redraws one of its faces." },
    { speaker: "TOMOYA", text: "That one looks suspiciously happy." },
    { speaker: "NAGISA", text: "Perhaps it had a very good day." },
    { speaker: "TOMOYA", text: "It lost its front door and got dragged through a storm." },
    { speaker: "NAGISA", text: "But everyone helped it." },
    { speaker: "", text: "That evening, they try out Nagisa's short play." },
    { speaker: "NAGISA", text: "It is only a rough idea." },
    { speaker: "AKIO", text: "All great performances begin as rough ideas. Then actors suffer until they become expensive ideas." },
    { speaker: "SANAE", text: "Please do your best, Nagisa." },
    { speaker: "TOMOYA", text: "Why am I still here?" },
    { speaker: "AKIO", text: "You carried the set. That makes you stage crew." },
    { speaker: "TOMOYA", text: "Stage crew doesn’t perform." },
    { speaker: "AKIO", text: "You spoke. Too late." },
    { speaker: "NAGISA", text: "There are two roles." },
    { speaker: "TOMOYA", text: "No." },
    { speaker: "NAGISA", text: "One is the person who returns home." },
    { speaker: "TOMOYA", text: "Still no." },
    { speaker: "NAGISA", text: "The other is the house." },
    { speaker: "TOMOYA", text: "Absolutely not." },
    { speaker: "AKIO", text: "I’ll be the house." },
    { speaker: "SANAE", text: "Akio-san, houses are quieter." },
    { speaker: "TOMOYA", text: "Which one has fewer lines?" },
    { speaker: "NAGISA", text: "The house." },
    { speaker: "TOMOYA", text: "Fine." },
    { speaker: "AKIO", text: "Coward." },
    { speaker: "TOMOYA", text: "You weren’t chosen." },
    { speaker: "NAGISA", text: "The house speaks first." },
    { speaker: "TOMOYA", text: "You said it had fewer lines, not that it had the worst lines." },
    { speaker: "NAGISA", text: "Please read." },
    { speaker: "TOMOYA", text: "Every evening, the house turns on its small light." },
    { speaker: "TOMOYA", text: "It does not know who may see it. It does not know when they will arrive." },
    { speaker: "AKIO", text: "Project your voice, boy." },
    { speaker: "TOMOYA", text: "The wind says nobody is coming. The rain says the road is empty. The house listens to both and keeps the light on anyway." },
    { speaker: "NAGISA", text: "I saw a light from the hill." },
    { speaker: "NAGISA", text: "I thought it might be waiting for someone." },
    { speaker: "TOMOYA", text: "The house says: I was." },
    { speaker: "NAGISA", text: "Then may I come in?" },
    { speaker: "TOMOYA", text: "You took a long time." },
    { speaker: "NAGISA", text: "I’m sorry." },
    { speaker: "TOMOYA", text: "It doesn’t say to apologize." },
    { speaker: "NAGISA", text: "That was not part of the play." },
    { speaker: "TOMOYA", text: "Oh." },
    { speaker: "NAGISA", text: "I have come home." },
    { speaker: "TOMOYA", text: "The light stays on." },
    { speaker: "NAGISA", text: "That is not the line." },
    { speaker: "TOMOYA", text: "It’s a better ending." },
    { speaker: "NAGISA", text: "But if the traveler is home, the light is not needed." },
    { speaker: "TOMOYA", text: "Maybe the house likes the way it looks." },
    { speaker: "AKIO", text: "Brilliant!" },
    { speaker: "AKIO", text: "Defiance! Wasteful electricity! The arrogance of architecture!" },
    { speaker: "SANAE", text: "I think it is warm." },
    { speaker: "AKIO", text: "Again!" },
    { speaker: "TOMOYA", text: "No." },
    { speaker: "AKIO", text: "The house has no passion." },
    { speaker: "TOMOYA", text: "The house is considering arson." },
    { speaker: "SANAE", text: "Then perhaps we should take a break." },
    { speaker: "", text: "Once the rain eases, Nagisa walks Tomoya to the bus stop." },
    { speaker: "TOMOYA", text: "It isn’t raining." },
    { speaker: "NAGISA", text: "There are still drops." },
    { speaker: "TOMOYA", text: "Those are falling from the roof." },
    { speaker: "NAGISA", text: "They are still rainwater." },
    { speaker: "TOMOYA", text: "You don’t have to walk me anywhere." },
    { speaker: "NAGISA", text: "I know." },
    { speaker: "TOMOYA", text: "Your house is behind you." },
    { speaker: "NAGISA", text: "Yes." },
    { speaker: "TOMOYA", text: "The bus stop is in the other direction." },
    { speaker: "NAGISA", text: "I know that too." },
    { speaker: "NAGISA", text: "Okazaki-san." },
    { speaker: "TOMOYA", text: "What?" },
    { speaker: "NAGISA", text: "Thank you for today." },
    { speaker: "TOMOYA", text: "I was paid in bread." },
    { speaker: "NAGISA", text: "You did much more work than one bread." },
    { speaker: "TOMOYA", text: "Then I’ll send an invoice." },
    { speaker: "NAGISA", text: "Please make it reasonable." },
    { speaker: "TOMOYA", text: "I’m charging by the building." },
    { speaker: "", text: "At the bus stop, Nagisa takes something from her notebook." },
    { speaker: "TOMOYA", text: "More work?" },
    { speaker: "NAGISA", text: "No." },
    { speaker: "TOMOYA", text: "A ticket?" },
    { speaker: "NAGISA", text: "It is a reservation." },
    { speaker: "TOMOYA", text: "For a performance with no date, no stage, and one actor." },
    { speaker: "NAGISA", text: "Yes." },
    { speaker: "TOMOYA", text: "This operation has serious management problems." },
    { speaker: "NAGISA", text: "There is also one audience member." },
    { speaker: "TOMOYA", text: "You assigned the seat without asking me." },
    { speaker: "NAGISA", text: "You may return it." },
    { speaker: "TOMOYA", text: "No refunds." },
    { speaker: "NAGISA", text: "Do you think anyone else will come?" },
    { speaker: "TOMOYA", text: "To the performance?" },
    { speaker: "NAGISA", text: "Yes." },
    { speaker: "TOMOYA", text: "Probably." },
    { speaker: "NAGISA", text: "Probably?" },
    { speaker: "TOMOYA", text: "If nobody does, you’ll still have a full front row." },
    { speaker: "NAGISA", text: "Then I will do my best." },
    { speaker: "TOMOYA", text: "Furukawa." },
    { speaker: "NAGISA", text: "Yes?" },
    { speaker: "TOMOYA", text: "Make the house’s lines shorter." },
    { speaker: "NAGISA", text: "I will consider it." },
    { speaker: "", text: "At home, Tomoya looks at the handmade ticket again." },
    { speaker: "TOMOYA", text: "Ridiculous." },
    { speaker: "", text: "Meanwhile, back at the bakery, Sanae reads Nagisa's revised ending." },
    { speaker: "SANAE", text: "That is a lovely ending." },
    { speaker: "NAGISA", text: "Okazaki-san thought of it." },
    { speaker: "SANAE", text: "I see." },
    { speaker: "NAGISA", text: "Mother?" },
    { speaker: "SANAE", text: "Yes?" },
    { speaker: "NAGISA", text: "Do you think one audience member is enough?" },
    { speaker: "SANAE", text: "If it is the person you most want to see the play, then one can be enough for the first performance." },
    { speaker: "NAGISA", text: "Then I will begin with one." }
];
